services:
  - type: web
    name: bruckentech
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn bruckentech.wsgi --access-logfile - --error-logfile -
    envVars:
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "bruckentech-ug.onrender.com,*.render.com"
      - key: DATABASE_URL
        fromDatabase:
          name: bruckentech_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
  
  - type: pgsql
    name: bruckentech_db
    version: 15
    plan: free
